services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpr_ams_be
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    ports:
      - "${HOST_PORT:-3010}:3000"
    volumes:
      - ./output:/app/output
      - ./public:/app/public
