import JoiDate from "@joi/date";
import JoiBase from "joi";

const Joi = JoiBase.extend(JoiDate);

const attendanceSchema = {
  query: Joi.object({
    get_all: Joi.boolean().optional().default(false),

    pagination: Joi.object({
      page: Joi.number().integer().min(1).default(1),
      limit: Joi.number().integer().min(1).max(100).default(10),
    })
      .default({
        page: 1,
        limit: 10,
      })
      .when("get_all", {
        is: false,
        then: Joi.optional(),
        otherwise: Joi.forbidden(),
      }),

    search: Joi.alternatives()
      .try(Joi.string().min(1).max(100), Joi.number().integer())
      .optional(),

    filter: Joi.object({
      isActive: Joi.boolean().optional(),

      status: Joi.string()
        .valid(
          "HADIR",
          "TERLAMBAT",
          "IZIN_CUTI",
          "ALPHA",
          "IZIN_SAKIT",
          "IZIN_SETENGAH_HARI",
        )
        .optional(),
    }),

    order_by: Joi.array()
      .items(
        Joi.object({
          field: Joi.string().valid("created_at", "updated_at").required(),
          direction: Joi.string().valid("asc", "desc").default("asc"),
        }),
      )
      .optional(),
  }),

  checkIn: Joi.object({
    date: Joi.date()
      .iso() // wajib format ISO 8601 (2026-02-28T08:00:00.000Z)
      .required()
      .messages({
        "date.base": "date must be a valid date",
        "date.format": "date must be in ISO 8601 format",
        "any.required": "date is required",
      }),
    checkInTime: Joi.date().iso().required().messages({
      "date.base": "checkInTime must be a valid date",
      "date.format": "checkInTime must be in ISO 8601 format",
      "any.required": "checkInTime is required",
    }),
    checkInLat: Joi.number().required().messages({
      "number.base": "latitude must be a number",
      "any.required": "latitude is required",
    }),
    checkInLong: Joi.number().required().messages({
      "number.base": "longitude must be a number",
      "any.required": "longitude is required",
    }),
    checkInPhoto: Joi.string().required().messages({
      "string.base": "checkInPhoto must be a string",
      "any.required": "checkInPhoto is required",
    }),
    checkInInsideRadius: Joi.boolean().required().messages({
      "boolean.base": "checkInInsideRadius must be a boolean",
      "any.required": "checkInInsideRadius is required",
    }),
    status: Joi.string()
      .valid(
        "HADIR",
        "TERLAMBAT",
        "IZIN_CUTI",
        "ALPHA",
        "IZIN_SAKIT",
        "IZIN_SETENGAH_HARI",
      )
      .required()
      .messages({
        "string.base": "status must be a string",
        "any.only":
          "status must be one of HADIR, TERLAMBAT, IZIN_CUTI, ALPHA, IZIN_SAKIT, IZIN_SETENGAH_HARI",
        "any.required": "status is required",
      }),
    points: Joi.number().integer().min(0).required().messages({
      "number.base": "points must be a number",
      "number.integer": "points must be an integer",
      "number.min": "points must be at least 0",
      "any.required": "points is required",
    }),
    isAutoGenerated: Joi.boolean().required().messages({
      "boolean.base": "isAutoGenerated must be a boolean",
      "any.required": "isAutoGenerated is required",
    }),
    employeeId: Joi.string().required().messages({
      "string.base": "employeeId must be a string",
      "any.required": "employeeId is required",
    }),
    branchId: Joi.string().required().messages({
      "string.base": "branchId must be a string",
      "any.required": "branchId is required",
    }),
  }),

  checkOut: Joi.object({
    checkOutTime: Joi.date().iso().required().messages({
      "date.base": "checkOutTime must be a valid date",
      "date.format": "checkOutTime must be in ISO 8601 format",
      "any.required": "checkOutTime is required",
    }),
    checkOutLat: Joi.number().required().messages({
      "number.base": "latitude must be a number",
      "any.required": "latitude is required",
    }),
    checkOutLong: Joi.number().required().messages({
      "number.base": "longitude must be a number",
      "any.required": "longitude is required",
    }),
    durationMinutes: Joi.number().integer().min(0).required().messages({
      "number.base": "durationMinutes must be a number",
      "number.integer": "durationMinutes must be an integer",
      "number.min": "durationMinutes must be at least 0",
      "any.required": "durationMinutes is required",
    }),
  }),
};

export { attendanceSchema };
