name: 🚀 CI/CD Development

on:
  push:
    branches:
      - DEV

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧰 Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🛠 Build Docker Image
        run: docker build --no-cache -t nevmock/bpr-api-dev:${{ github.sha }} -t nevmock/bpr-api-dev:latest .

      - name: 📤 Push Docker Image
        run: |
          docker push nevmock/bpr-api-dev:${{ github.sha }}
          docker push nevmock/bpr-api-dev:latest

      - name: 📤 Push Docker Image
        run: docker push nevmock/bpr-api-dev:latest

      - name: 🚢 Deploy to VPS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🧹 Cleaning old images..."
            docker image prune -af

            echo "🔁 Pulling latest Docker image..."
            docker pull nevmock/bpr-api-dev:latest

            echo "🛑 Stopping and removing old container (if exists)..."
            docker stop bpr-api-dev || true
            docker rm bpr-api-dev || true

            echo "🚀 Running new container..."
            docker run -d \
              --name bpr-api-dev \
              --network dev-postgresql-network \
              --restart unless-stopped \
              -e NODE_ENV="development" \
              -e PORT="3000" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -p "${{ secrets.PORT }}":3000 \
              -v bpr-api-dev:/app/public \
              nevmock/bpr-api-dev:latest
            
            echo "🔄 Running Prisma migrations..."
            docker exec bpr-api-dev npx prisma migrate deploy --preview-feature

            echo "✅ Deployment completed successfully!"